### ISSUE TITLE
Poll viewer (student)

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#117]
**Please describe what has to be done**

- [x] Design Complete/Approved
- [ ] Code Created
- [ ] Code approved/merged

**Additional context**

See sitemap and slide 24

**Comment by ashwinc12** [comment]
<img width="1028" alt="Screen Shot 2020-04-24 at 12 07 25 PM" src="https://user-images.githubusercontent.com/25444441/80233261-31c28e00-8624-11ea-87ec-da52a6bd8490.png">

**Comment by ashwinc12** [comment]
<img width="1440" alt="Screen Shot 2020-04-24 at 12 42 47 PM" src="https://user-images.githubusercontent.com/25444441/80236508-2a51b380-8629-11ea-9727-bb41058d35cd.png">

**Comment by ashwinc12** [comment]
Current status of page. Most likely need to make the A, B, C, and D buttons and have a submit page. Can be done in the future with the backend team.

**Comment by hbh7** [comment]
I like how it's looking so far. I think the circles from the mockup were nice though and probably worthwhile adding. For the sake of easy clicking, it may be nice to wrap each answer in a bubble too of a different color so it's obvious where to click.
