### ISSUE TITLE
Account info page

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#118]
**Please describe what has to be done**

- [x] Design Complete/Approved
- [x] Code Created
- [ ] Code approved/merged

**Additional context**

See sitemap and slide 7

**Comment by ashwinc12** [comment]
Current state
![Screen Shot 2020-03-24 at 4 53 31 PM](https://user-images.githubusercontent.com/25444441/77476009-1e878d00-6df0-11ea-8940-987d8f51d5d0.png)

**Comment by ashwinc12** [comment]
Added forms
![Screen Shot 2020-03-24 at 5 32 44 PM](https://user-images.githubusercontent.com/25444441/77479094-89879280-6df5-11ea-92d7-663a2a71f43f.png)

**Comment by ashwinc12** [comment]
Additional styling will be done after working on the other pages that I self-assigned. I'm having some trouble adjusting some of the stylings. However, the functionality is there

**Comment by ashwinc12** [comment]
All can be located within the "account-info" branch

**Comment by ashwinc12** [comment]
Added CSS to the forms. Need some help to center the header
![Screen Shot 2020-03-26 at 7 26 02 PM](https://user-images.githubusercontent.com/25444441/77706087-c4c1c700-6f97-11ea-843c-701b08bb6acb.png)
