### ISSUE TITLE
Change password page

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#119]
**Please describe what has to be done**

- [x] Design Complete/Approved
- [x] Code Created
- [ ] Code approved/merged

**Additional context**

See sitemap and slide 21

**Comment by ashwinc12** [comment]
![Screen Shot 2020-03-26 at 2 12 28 PM](https://user-images.githubusercontent.com/25444441/77681566-e3aa6400-6f6b-11ea-8546-082c2cd1812c.png)
Design Diagram for the page, which the styling of the #118 page

**Comment by ashwinc12** [comment]
All commits can be found within the 'change-password' branch

**Comment by ashwinc12** [comment]
![Screen Shot 2020-03-26 at 3 32 00 PM](https://user-images.githubusercontent.com/25444441/77688751-f8402980-6f76-11ea-8167-e8387f4de4bf.png)

**Comment by ashwinc12** [comment]
The same status as #118 where I am struggling to add CSS to the `<label>` tag, but the functionality is there.  Both will be adjusted after the next meeting hopefully, but done for now.

**Comment by ashwinc12** [comment]
![Screen Shot 2020-03-26 at 7 31 43 PM](https://user-images.githubusercontent.com/25444441/77706360-8d074f00-6f98-11ea-9da8-11548f9aee30.png)

**Comment by ashwinc12** [comment]
Added CSS to the forms, but need. help to center change password text. Can be done in tomorrow's meeting

**Comment by hbh7** [comment]
No longer necessary as per our discussion today, likely need to delete the branch still though. Is it change-password?

**Comment by ashwinc12** [comment]
Functionality found somewhere else. Closing
