### ISSUE TITLE
Privacy page

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#122]
**Please describe what has to be done**

- [x] Design Complete/Approved
- [ ] Code Created
- [ ] Code approved/merged

**Additional context**

See sitemap and slide 25

**Comment by ashwinc12** [comment]
Doesn't seem like anyone started this page or began working on it ... I'll self-assign this.

**Comment by ashwinc12** [comment]
Simple privacy page. Words can be tweaked if needed. Header is eventually going to be changed and the footer is going to be added eventually too as well.
![Screen Shot 2020-04-15 at 3 42 52 PM](https://user-images.githubusercontent.com/25444441/79381378-e1667480-7f2f-11ea-9afe-500ac6402457.png)

**Comment by ashwinc12** [comment]
Making pull request now
