### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#125]
**Please describe what has to be done**

- [x] Design Complete/Approved
- [ ] Code Created
- [ ] Code approved/merged

**Additional context**

See sitemap and slide 9

**Comment by ashwinc12** [comment]
Designed to look this with the styling of the previous pages
<img width="1024" alt="Screen Shot 2020-04-02 at 12 59 29 PM" src="https://user-images.githubusercontent.com/25444441/78277043-dea46200-74e1-11ea-9505-852399a733a9.png">

**Comment by ashwinc12** [comment]
Current status
![Screen Shot 2020-04-10 at 1 03 48 PM](https://user-images.githubusercontent.com/25444441/79008638-cceb3c00-7b2b-11ea-9996-984422bcb7ce.png)

**Comment by ashwinc12** [comment]
For some reason, MDB containers aren't letting me move the right side logos up. I'll clean it up next week and add the hyperlinks.

**Comment by hbh7** [comment]
Let's merge this into the about page. See #120

**Comment by hbh7** [comment]
@ashwinc12 ok for me to delete the contact-us branch too?

**Comment by ashwinc12** [comment]
Yeah, feel free. Thanks
