### ISSUE TITLE
Footer component/template 

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#129]
**Please describe what has to be done**

- [ ] Pollbuddy written somewhere
- [x] Helpful links (about, log in, contact, etc.) 
- [x] Probably centered on the page 
- [ ] Maybe the logo
- [x] Probably "An RCOS Project" with or without their logo 
- [ ] Anything else that makes it look good and be more useful

**Additional context**
See slide 31

**Comment by annieshi6** [comment]
![Screenshot from 2020-04-30 03-47-47](https://user-images.githubusercontent.com/31863368/80685674-9141f300-8a95-11ea-8af7-47cf0653fe6a.png)
what it looks like right now, based loosely off the sitemap version
lmk if there's anything we should do differently

**Comment by annieshi6** [comment]
![Screenshot from 2020-04-30 06-13-03](https://user-images.githubusercontent.com/31863368/80699286-b3de0700-8aa9-11ea-9b37-b6db4e88f075.png)
Update: links shorten, also added link to privacy policy
contact link is still to someemail@yeah.com
links also become brighter on hover!

**Comment by hbh7** [comment]
Add Poll Buddy Text (probably to the right but could be moved around in experimentation)

**Comment by hbh7** [comment]
Fixed in #212
