### ISSUE TITLE
Selecting a main font

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#135]
**Please describe what has to be done**
Everyone go out and pick their top 1-3 fonts, post links here and we'll vote on a favorite

**Comment by annieshi6** [comment]
[Open Sans](https://fonts.google.com/specimen/Open+Sans)
[Roboto](https://fonts.google.com/specimen/Roboto)
These fonts seem to be popular pairings with Fredoka.

**Comment by hbh7** [comment]
Tbh I think Roboto was already veto'd by a few people lol. Open Sans perhaps though.

**Comment by annieshi6** [comment]
Hmm.. it looks like Roboto is in use right now, but the style is extremely thin.

**Comment by hbh7** [comment]
Is there a thicker one perhaps?

**Comment by hbh7** [comment]
I think I like this https://fonts.google.com/specimen/Baloo+2

![image](https://user-images.githubusercontent.com/5050375/87263256-9dc9cb00-c48a-11ea-95b6-e9173034d07b.png)
![image](https://user-images.githubusercontent.com/5050375/87263263-a02c2500-c48a-11ea-8078-64ddeed850e5.png)
![image](https://user-images.githubusercontent.com/5050375/87263266-a3bfac00-c48a-11ea-82b7-2fd3eed99dce.png)

It feels professional enough without being hard or sharp (there's slight rounding without being silly) or generic. I think it fits our feel pretty good. Especially small lettering feels really nice imo. 

Thoughts? Am I way off basis? lol

React with 👍 or 👎

**Comment by schans2** [comment]
Yeah, I like the slight roundedness. It gives off a classroom-y feeling.

**Comment by hbh7** [comment]
Ok it's been 10 days now and the (small) general consensus seems to like this font, so that's what we'll use then. Will create a new issue to implement it.
