### ISSUE TITLE
React outdated, many (tens of thousands of) security issues, needs to be updated

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#145]
**Please describe what has to be done**
Looks like we're on React-Scripts 3.2.0, can go up to 3.4.1. Seems we need to go through the intermediate versions but I could be wrong. See directions below. This should theoretically update all the react stuff I think, but again could be wrong. 

**Additional context**
https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md

**Comment by ashwinc12** [comment]
Just updated this to version 3.4.1. Creating a pull request now.
`npm install --save --save-exact react-scripts@3.4.1`
