### ISSUE TITLE
the pollCode page looks off center

### ISSUE THREAD

**Issue by neha-deshpande001** [PollBuddy/PollBuddy#155]
**Describe the bug**
Pretty self-explanatory.  It looks like the components of the pollCode page are not in the center.

**To Reproduce**
1. Go to http://localhost:3000/pollCode

**Expected behavior**
The components should be centered.

**Screenshots**
![the pollCode page looks off center](https://user-images.githubusercontent.com/37943727/79652045-8f1b9280-817f-11ea-9c83-c6e0a11e82cc.png)

**Comment by hbh7** [comment]
Merged
