### ISSUE TITLE
Privacy Page Header

### ISSUE THREAD

**Issue by ashwinc12** [PollBuddy/PollBuddy#165]
The privacy page was not merged when the changing of the header occurred. I'll go through and switch the header and try to clean up the page as well

**Comment by ashwinc12** [comment]
Current Status after changes
![Screen Shot 2020-04-24 at 2 10 22 PM](https://user-images.githubusercontent.com/25444441/80243671-a225db00-8635-11ea-9043-b6e63d197da1.png)

**Comment by hbh7** [comment]
Merged
