### ISSUE TITLE
Header and consistent page size

### ISSUE THREAD

**Issue by neha-deshpande001** [PollBuddy/PollBuddy#167]
**Please describe what has to be done**
As of now, the header is a constant 72px, which means there is 72px of the rest of the page that the user needs to scroll down to see. Make the size of each page consistent so that the user doesn't need to scroll down.

**Comment by annieshi6** [comment]
It seems like a lot of the pages were built using a height of 100vh to vertically center and that's what's causing the problem. I'm going through them as I implement the footer and changing them to just use margins to create spacing instead.
