### ISSUE TITLE
Header dropdown menu

### ISSUE THREAD

**Issue by neha-deshpande001** [PollBuddy/PollBuddy#174]
**Please describe what has to be done**
Create a dropdown menu in the header so that multiple pages are accessible both when the user is logged in and logged out.

**Additional context**
These are the following pages that we have so far, listed alphabetically, that should be displayed for each user. This list should be updated as we add more pages.

**Teacher, logged in:**
- accountinfo
- classcreation
- lesson/lessons
- myclasses
- pollDataView
- privacy
- settings

**Student, logged in:**
- accountinfo
- lesson/lessons
- myclasses
- pollDataView
- privacy
- settings

**Any user, logged out:**
- forgotpassword
- homepage/pollCode (These will be combined into the homepage)
- login
- privacy
- registerDefault
- registerWithPollBuddy
- registerWithSchool
- resetPassword

**Comment by annieshi6** [comment]
For users logged out,
- home page is linked through the logo
- forgot password should be already be linked on login page
- register(pb), register(school) should be linked on register(default), which should be linked on login
- reset password should be linked on forgot password (I think??)
I don't think it makes sense to list all those pages to a logged out user, so I'd say only login and privacy are necessary. If you wanted to list register(default) too, that'd be fine but then on the login page it should just be a hyperlink "Don't have an account?", as opposed to a another register button.
Log out should also be an option for logged in users.

**Comment by hbh7** [comment]
We'll probably want to address https://github.com/PollBuddy/PollBuddy/issues/179 before doing too much on this. I think we have 2 different sitemaps WIP so we'll want to probably pick one and finalize it as much as we can.

**Comment by hbh7** [comment]
Updated list: 
Login or Logout (Dynamic)
Register (Dynamic: Visible when not logged in only)
Account (Dynamic: Visible when logged in only)
Enter Poll Code (Always)
Groups (Dynamic: Visible when logged in only)
Settings (Todo: Does this page even exist/is relevant anymore? Would be visible when logged in only though)

I like the idea of the login/register options always being visible though... Should we maybe consider a custom header for just the homepage, as that's where it'd be most relevant? Open to thoughts

**Comment by hbh7** [comment]
Added history page to above list. See issue on PollHistory here: #116

**Comment by hbh7** [comment]
Updates from #294:

Remaining todo items: 
Make the following menu items visible only when the user is logged in: Logout, Account, Groups, History, and Settings.
Make the following menu items visible only when the user is logged out: Login and Register.
Make sure that each menu item links to the correct path (particularly History and Settings).
