### ISSUE TITLE
Create Site Map

### ISSUE THREAD

**Issue by burgus7** [PollBuddy/PollBuddy#179]
Create a visual and graphic site map to chart the (1) User flow/experience and (2) the information flow.
Update the links between pages to match the site map.

**Comment by hbh7** [comment]
Some WIP Resources: 

https://docs.google.com/document/d/1gmCMa8PSnYsf6bunaQcudKa8i9qi9_cCJ2CDH6PEaVw/edit

https://docs.google.com/presentation/d/1siNQbw_bLO20ygIsLUfZgWmDe3D2jj4ZP4kH2MfJq7A/edit

https://docs.google.com/document/d/1kFdjwiE4_POgcTDqXK-bcnz4RAeLG6yaF2RxLzkNDrE/edit

**Comment by burgus7** [comment]
https://draft.io/jubvd

**Comment by hbh7** [comment]
Looking good, I just want to get some other reviews too to make sure we're not missing anything.

**Comment by hbh7** [comment]
Finished in #242
