### ISSUE TITLE
Repo is ugly

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#182]
**Please describe what has to be done**
The repo is ugly; there are no pictures. We should add screenshots of different pages and describe them. 

**Additional context**
I was looking for a self hosted budgeting app and any repo without pictures was instantly closed because I don't want to go through setting it up if I then just decide it's ugly and I hate it lol. People viewing Poll Buddy shouldn't be faced with the same problem.

**Comment by jinh5** [comment]
For the repo, where should the screenshots and descriptions be? Would it be in the read.me, wiki, somewhere else??

**Comment by hbh7** [comment]
I'm thinking make a new category at the same level but above "How to run the app" with a screenshot of the homepage, about page, FAQ page, /login page, groups page, https://pollbuddy.app/polls/607e502721601577468b4ba8/view page, and https://pollbuddy.app/polls/607e502721601577468b4ba8/results page. 

If you could size them so the content mostly fills the window (with all windows being the exact same size), that would be ideal. Thanks!

**Comment by jinh5** [comment]
So this means creating a new page in the wiki right? Also when you talk about sizing could you clarify what you mean by content mostly filling the window? Do you mean making the images fill up as much space as possible in the wiki?

**Comment by hbh7** [comment]
Sorry, I meant the main readme.md, I thought I said that but I clearly didn't. By sizing, I just mean maximize the Poll Buddy page window on your computer, and set the page zoom level to 100% or 110%, then take the screenshot. It should then automatically fit nicely in the readme once placed there. Also, put the images in the resources repo for storage and then link to them in the readme.

**Comment by jinh5** [comment]
where is the resources repo?

**Comment by hbh7** [comment]
https://github.com/PollBuddy/Resources

**Comment by jinh5** [comment]
Is there a particular name you would like to give the new category?

**Comment by hbh7** [comment]
I'm thinking a folder called "README Data" with a folder in that called "Images", so it matches the one for Wiki data.
