### ISSUE TITLE
Change homepage blurb

### ISSUE THREAD

**Issue by neha-deshpande001** [PollBuddy/PollBuddy#183]
**Please describe what has to be done**
Change the homepage blurb to something more descriptive and appealing.

**Comment by hbh7** [comment]
New blurb: 

Poll Buddy is an interactive questionnaire platform that aims to be an enjoyable and easy to use way to collect answers and insights from a group of people. 

Thoughts? 👍 or 👎

**Comment by hbh7** [comment]
I guess we'll stick with that for now then. Remaining todo item here then would be to change it on the website

**Comment by hbh7** [comment]
Done in #241
