### ISSUE TITLE
lesson page dropdown menu not working

### ISSUE THREAD

**Issue by neha-deshpande001** [PollBuddy/PollBuddy#191]
**Describe the bug**
lesson page dropdown menu not working. It looks like a button on top of two side-by-side links. The "simple addition" button should be a dropdown menu and the "simple addition" and "multiplication" links should be two options. See screenshot. 

**Screenshots**

![image](https://user-images.githubusercontent.com/37943727/84332886-1a9c1900-ab5c-11ea-8c00-ce726bde04dd.png)

**Comment by hbh7** [comment]
I think that whole page in general just needs a lot of work. We need to evaluate where it's at and how to get it to where we want it. May be a good discussion topic for 2020/06/16's session

**Comment by hbh7** [comment]
Closed due to being outdated and irrelevant
