### ISSUE TITLE
Update description on rcos.io

### ISSUE THREAD

**Issue by neha-deshpande001** [PollBuddy/PollBuddy#192]
**Please describe what has to be done**
Currently, rcos.io has an outdated description of Poll Buddy. We should add a better description and some screenshots. Maybe just copy-paste the readme when that gets updated

**Comment by hbh7** [comment]
Good idea. We can probably copy from the proposal, and maybe integrate a shorter blurb into the footer later too if we want, since iirc we scrapped the about us page.

**Comment by hbh7** [comment]
Definitely no blurb in the footer now with the new design, just the homepage (#183) and rcos.io page. I think the new proposed blurb is descriptive enough that that's all we'll need for the rcos.io page, but we could expand if anyone wants.

**Comment by hbh7** [comment]
Updated
