### ISSUE TITLE
Media queries for different display sizes

### ISSUE THREAD

**Issue by neha-deshpande001** [PollBuddy/PollBuddy#198]
**Please describe what has to be done**
If the window display size is under 500px (or something similar, look into common phone resolutions and validate a few)
- [x] For pages with the box, remove the box
- [x] Resize buttons so all the text fits
- [x] Resize text boxes so placeholder text fits
- [x] Resize the chart in the pollDataView page

Likely a lot more things we'll discover in time. This is a good starting point though

**Comment by hbh7** [comment]
Sure, will set up some reference material or something in a little bit

**Comment by hbh7** [comment]
This is definitely important as the mobile view needs a lot of work. I updated the original post slightly with check boxes

**Comment by annieshi6** [comment]
Been meaning to do this for a while and I finally started w the footer last week!
Right now my breakpoints for the footer are just where text starts wrapping but will do further research?

**Comment by hbh7** [comment]
Great! That's probably a good starting point at least. I'm not sure what makes the most sense but dynamic wrapping is probably the right way to go about it.

**Comment by hbh7** [comment]
Fixed in #397
