### ISSUE TITLE
Do we need labels above all text inputs for accessibility?

### ISSUE THREAD

**Issue by neha-deshpande001** [PollBuddy/PollBuddy#199]
Some pages have a label, some don't.
Some pages have a placeholder, some don't.
Should we use emojis for placeholders/labels?

Figure this out and make it unified for each page

**Comment by hbh7** [comment]
Yes, all input fields should have a label. I think you were looking at some/all of these in the universal stylesheet branch so it may be pretty easy to just double check and fix the (hopefully) few problematic ones that remain.

It seems that emojis tend to not give the look we want so I guess they'll stay out.

**Comment by hbh7** [comment]
Fixed in #211
