### ISSUE TITLE
Input onFocus styling

### ISSUE THREAD

**Issue by schans2** [PollBuddy/PollBuddy#215]
**Is your feature request related to a problem? Please describe.**
In my opinion, input fields throughout the site would look better with some kind of stylistic tweak when focused.

**Describe the solution you'd like**
My vision of this is having an outline fade in/out on focus in/out (0.3s is usually the transition time I use for these kinds of things). For its color, I'm thinking of either the base or light purple in the style guide. Feel free to comment any other suggestions, thanks!

**Comment by annieshi6** [comment]
I tried this out on the flat-design branch login page. Let me know what you think?

**Comment by schans2** [comment]
Nice job, that's basically what I was thinking of, I like it!

**Comment by hbh7** [comment]
I believe you can review it even if you're not listed as a reviewer, but definitely let me know if I'm mistaken

**Comment by hbh7** [comment]
(records keeping)
We reviewed this in the 07/21/2020 meeting and decided this looked good. We had mixed opinions on whether the placeholder should remain or not when clicked but I think it would be great if you could share a picture with and without it for comparison, and then we can decide which we think looks best before PR'ing and merging.

**Comment by annieshi6** [comment]
![Screenshot from 2020-07-24 01-59-27](https://user-images.githubusercontent.com/31863368/88365367-c471e680-cd53-11ea-9dfc-d76134c37c0f.png)
![Screenshot from 2020-07-24 02-01-36](https://user-images.githubusercontent.com/31863368/88365381-cc318b00-cd53-11ea-9173-cc82672fb898.png)
PR probably won't come until the new look has been applied across all pages

**Comment by hbh7** [comment]
React with 👍 or 👎  to show your thoughts on this. (👍 means keep placeholder text)

**Comment by hbh7** [comment]
Fixed in #243
