### ISSUE TITLE
Implement new main font

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#228]
**Please describe what has to be done**
Our new font has been chosen, and now needs to be implemented. 

**Additional context**
Should ideally be as simple as setting it somewhere in the main CSS file. 
Original issue: https://github.com/PollBuddy/PollBuddy/issues/135
Font: [Baloo 2](https://fonts.google.com/specimen/Baloo+2)

**Comment by annieshi6** [comment]
Not sure what this is about, but Baloo 2 seems to take up a lot more space vertically? hmmm...
I tried with Roboto too and it seems to take up the same vertical space as monospace, so I assume this is a font issue.
![Screenshot from 2020-07-24 01-52-49](https://user-images.githubusercontent.com/31863368/88364362-9b038b80-cd50-11ea-85c9-5274160ef51a.png)
![Screenshot from 2020-07-24 01-52-29](https://user-images.githubusercontent.com/31863368/88364383-a951a780-cd50-11ea-8d35-ff2ab5720c7d.png)

**Comment by hbh7** [comment]
Are you using the default / regular 400 style? 

I see what you mean by the height increase. Very slight though at least. I wonder if we can compensate with changing the line height or spacing somewhere in CSS, coupled with maybe an extra pt or two of actual letter size.

**Comment by hbh7** [comment]
Try this perhaps https://www.w3schools.com/cssref/pr_dim_line-height.asp

**Comment by annieshi6** [comment]
TIL line-height: normal is defined by the font-family (like why did they do that but ok sure). It looks like this font's line-height is ~1.6, whereas normal for most fonts is ~1.2 so forcing a line-height of 1.2 did the trick :+1:

**Comment by hbh7** [comment]
Fixed in #243
