### ISSUE TITLE
Confirm all password entry fields look the same 

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#246]
**Please describe what has to be done**
Validate this is true on all pages with password fields:
Same character used: ●
Same number of characters used: 12

**Comment by annieshi6** [comment]
I think I already did this in the theme update and I was the one that changed it to 12 circles but will do a more thorough sweep

**Comment by hbh7** [comment]
Perfect :)

**Comment by annieshi6** [comment]
^ actually changed to using • and restyled so what you type looks like the placeholder

**Comment by hbh7** [comment]
Complete in #288
