### ISSUE TITLE
questionEditor branch revival

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#255]
**Please describe what has to be done**
The questionEditor branch is very outdated but seems to have useful code in it still. I'm looking for someone to pull out the relevant code into a new fresh branch based on current code and integrate it there. I think the key files are questionEditor.js, questionEditor.scss but it's not impossible there's more.

**Comment by toneofgrey** [comment]
Main commits for this old branch are the two js files in the components folder in frontend - classEditor.js and questionEditor.js.
The function of classEditor.js has already been replaced by GroupEditor, I still have to talk to Nicholas about the PollEditor.js to see if it has replaced questionEditor.js.

**Comment by hbh7** [comment]
Great!

**Comment by hbh7** [comment]
Fixed in #328
