### ISSUE TITLE
Update main README with new installation directions

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#260]
**Please describe what has to be done**

- [x] "Accessing the app" section: frontend/backend access URLs need to be updated to the new method. (localhost:7655, /api, etc.)
- [x] "Accessing the app" section: add reporting URL
- [x] "Accessing the app" section: modify database access part to explain how to make it work (changing the docker-compose.yml file)
- [x] "Docker Method": explain the -d option and indicate that it can be left out (and why)
- [x] "Prerequisites": change Docker and Docker-Compose to be links to installation instructions
- [x] Add logo to top, centered
- [x] Add mention/link to the Docker post-installation steps so commands don't need sudo
- [x] Clarify the .env file creation (copy and paste the file next to the existing one but with the new name)

**Comment by hbh7** [comment]
This is probably a good page to link to for Docker installation
https://docs.docker.com/get-docker/

**Comment by Shadowsoftime99** [comment]
One other thing that came up during a new member's (mine) setup:

-Add mention/link to the Docker post-installation steps so commands don't need `sudo`
