### ISSUE TITLE
Homepage poll code placeholder adjustment

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#261]
**Please describe what has to be done**
The text box for "Already have a Poll Code? Enter it here:" has "K30SW8" in it which may be confusing, a prefix of "Ex: " would help I think. May also be worthwhile changing it to something with a hidden meaning for fun.

**Comment by annieshi6** [comment]
Was there every discussion about the poll codes? Like whether they'd all be a fixed size, how they're generated, etc

**Comment by hbh7** [comment]
I mentioned that in another issue but yeah I don't think we ever discussed it. Was going to bring it up at the next meeting. I like the size of 6 a-z0-9 characters but we can do whichever makes the most sense.

**Comment by hbh7** [comment]
(2020/10/02 Meeting notes): We will indeed be going with a 6 character a-z0-9 code. Visually, use uppercase letters. Perhaps a placeholder of PB2020 or something more clever idk

**Comment by annieshi6** [comment]
P8C0D3?

**Comment by hbh7** [comment]
Fixed in #320
