### ISSUE TITLE
Groups page functionality

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#268]
**Please describe what has to be done**

- [x] Should request from the backend what groups the user is a part of. 
- [x] Then, dynamically generate boxes (of equal width) for each group. 
- [x] Display the loading wheel while waiting for data. 
- [x] Display an error if something goes wrong in the loading process. 
- [x] Display a relevant message if a user is part of no groups. 
- [x] Bounce to /login if user is not logged in

**Comment by hbh7** [comment]
Converted paragraph to checkboxes, added login one

**Comment by simar-singh** [comment]
Created function to bounce user to login if they are not logged in.

**Comment by simar-singh** [comment]
Currently waiting for /me/groups api route to correctly output id and label objects

**Comment by hbh7** [comment]
Done in #590
