### ISSUE TITLE
Login With School page dropdown is unreadable

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#280]
**Describe the bug**
The font color for the dropdown doesn't work right so the menu options are invisible. 

**To Reproduce**
1. Go to /login/school
2. Click on enter school name box
3. See text color is wrong

**Expected behavior**
Should match the /register/school page look

**Screenshots**
![image](https://user-images.githubusercontent.com/5050375/95255950-28069e80-07f0-11eb-923d-635e7c7988b0.png)

**Comment by annieshi6** [comment]
i previously restyled the register/school autocomplete so should be as simple as adding the class! maybe some changes to the html

**Comment by edmgt** [comment]
Hey, (random PR incoming) I opened https://github.com/PollBuddy/PollBuddy/pull/287 which should fix this bug + extracts school autoselect to a new component. I made it a draft in case it's not useful but let me know if you fancy reviewing it 🙂

**Comment by EthanTuttle** [comment]
So I wanted to work on this since it seemed an easy fix, just change the hex colors of the backgrounds, and I did it but now I'm getting white lines on the top and bottom that annoy me.
![Screenshot (1)](https://user-images.githubusercontent.com/70231237/95918705-45041a00-0d7a-11eb-8baa-7eb992d075a8.png)

**Comment by EthanTuttle** [comment]
I also just realized someone else took care of this lmao. But if anyone knows the answer to this anyway I'd love to know

**Comment by annieshi6** [comment]
There's probably a surrounding container so I assume you would just style that too.

**Comment by hbh7** [comment]
Lol @EthanTuttle no worries. I think the dark box idea like that should be explored for sure but probably later on down the line. For now though, this is taken care of in #287
