### ISSUE TITLE
Login With School Page functionality

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#281]
**Please describe what has to be done**

- [x] Populate the schools dropdown with a call from the backend
- [x] Probably use the loading wheel since the only thing you can do on this page is select a school, so you need that to be ready
- [x] Remove the CAS button, send to CAS backend URL if selecting RPI. This should probably be handled by the backend. Ex: Backend call returns an array of schools and URLs to redirect to. This functionality may or may not exist in the backend so an issue may need to be made for that.

**Comment by lulujoe** [comment]
The first request is to get school info from the backend. Does that means we have school info in the MongoDB database? Also, are there some ways to check the data and tables in MongoBD database? Currently I know we have a mongoConnection.js file but don't know how to check data directly.

**Comment by hbh7** [comment]
I believe someone else is working on a method to get the list of schools so that's TBD. Maybe talk with them. There should be an issue. As for how to get data from the database, explore the users.js and related files for a bunch of examples.

**Comment by hbh7** [comment]
Just needs the loading wheel now

**Comment by hbh7** [comment]
Unassigning due to semester turnover. Future developer, please check for an existing branch when taking this issue, as some work may be in progress that you could continue and finish. Existing developer, please feel free to re-add yourself if I've made a mistake.

**Comment by hbh7** [comment]
Done in #687
