### ISSUE TITLE
Register With School Page functionality

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#282]
**Please describe what has to be done**

- [x] Populate the schools dropdown with a call from the backend
- [x] Probably use the loading wheel since the only thing you can do on this page is select a school, so you need that to be ready
- [x] Remove the CAS button, send to CAS backend URL if selecting RPI. This should probably be handled by the backend. Ex: Backend call returns an array of schools and URLs to redirect to. This functionality may or may not exist in the backend so an issue may need to be made for that.

**Comment by doboianh** [comment]
Can i do this issue

**Comment by hbh7** [comment]
@doboianh Looks like it's currently assigned to @lyndseytoft, so you'll have to find one that no one is currently assigned to. Sorry about that

**Comment by hbh7** [comment]
Unassigning due to semester turnover. Future developer, please check for an existing branch when taking this issue, as some work may be in progress that you could continue and finish. Existing developer, please feel free to re-add yourself if I've made a mistake.

**Comment by hbh7** [comment]
Done in #687
