### ISSUE TITLE
header-dropdown branch revival

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#284]
**Please describe what has to be done**
The header-dropdown branch was WIP by @emanua who does not appear to be participating this semester. The branch seems to have useful code in it still. I'm looking for someone to pull out the relevant code into a new fresh branch based on current code and integrate it there, or just finish this one up so it's ready to PR and merge.

**Comment by jssunray34** [comment]
I reviewed this branch, and it should be okay to delete this issue (see #174).

**Comment by hbh7** [comment]
Great, thanks
