### ISSUE TITLE
Join group page

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#290]
**Please describe what has to be done**

- [x] New page at /groups/:groupID/join
- [ ] Shows details of the group to join (only if user passes join permission checks)
- [x] Join permissions check - group must be open join by ID, or user must be added to group's allowed to join users list
- [x] Ask if you're sure you'd like to join this group or cancel
- [x] Bounce to /login if user is not logged in
- [x] Submit request to backend to add user to group
- [x] Redirect to /groups afterward, or to that specific group's page (whichever seems to make more sense)

**Additional context**

**Comment by EthanTuttle** [comment]
This can probably be deleted, Jody's going to make this unnecessary with issue #290 by just linking join group to a new page
