### ISSUE TITLE
MongoDB unique values and indexing

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#299]
**Please describe what has to be done**
As seen in https://github.com/PollBuddy/PollBuddy/pull/291, indexing can be used for value uniqueness. We should look into doing this on other fields.

**Comment by aidan-lane** [comment]
As quick note, I added a unique field to email in users when the database is created in mongoconnection.js

**Comment by hbh7** [comment]
Done in #404 (PR not found 😝)
