### ISSUE TITLE
Registration client-side validation update for new rules

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#307]
**Please describe what has to be done**
Ensure that user registration details are validated prior to submission to the backend. Also show helpful warnings/error messages if criteria isn't met. Probably always show password requirements as a dropdown underneath the password box once the user starts typing. Username requirements can be hidden until error I think. 

- [x] First name validation
- [x] Last name validation
- [x] User name validation
- [x] Email validation
- [x] Password validation

**Additional context**
See https://github.com/PollBuddy/PollBuddy/issues/298 and https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-User-Data

**Comment by lulujoe** [comment]
What should be the userName and password requirements? I assume email requirement is xxx@xxx.xxx

**Comment by hbh7** [comment]
See https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-User-Data

**Comment by hbh7** [comment]
Finished in #400
