### ISSUE TITLE
Backend route testing, fixing: users: /:id/edit

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#345]
**Please describe what has to be done**
Test the route for defined functionality, proper error handling, input validation, etc. **See comments for more details**. 

**Additional context**
Prerequisite: https://github.com/PollBuddy/PollBuddy/issues/344

**Comment by hbh7** [comment]
Also validate that the returned data format adheres to https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Backend-Overview

**Comment by hbh7** [comment]
New specifications:
- [ ] Should accept JSON Object
- [ ] Only send changed fields
- [ ] Accepted fields:

* FirstName: String
* LastName: String
* UserName: String
* Email: String
* Password: String

Notes:
This route requires that a user has `SiteAdmin` set to `true` on their own user account, or that the app is running in development mode. 

Backend should check for the existence of each key and validate each, and then if no errors, overwrite each saved value with the provided ones. 

Upon success, return result = success and data as the same that /:id would give so the frontend can update its cache. Upon failure, return result = failure and error message as whatever the validation error is, or that there was a database problem.

Please also note that the fields above are written in PascalCase to match the database data. However, the backend is a translation layer for the frontend, and therefore it should accept and return data in camelCase instead, as that is the format the frontend uses. This should simply mean changing the case of the first letter.

Special cases: 
 * Protected Values:
   * Should respect values that have a `<keyname>Locked` set to `true` by not allowing them to be changed. This applies to `FirstName`, `LastName`, `UserName`, and `Email`. Additionally, if `SchoolAffiliation` is set, `Password` changing should be locked too.

**Comment by PrinxeShamar** [comment]
On the site admin requirement. This would need a user to be logged in right?

**Comment by hbh7** [comment]
Yep, you're right, login required too. I'll make a note
