### ISSUE TITLE
Backend route testing, fixing: users: /:id/

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#347]
**Please describe what has to be done**
Test the route for defined functionality. 

**Additional context**
Prerequisite: https://github.com/PollBuddy/PollBuddy/issues/346

**Comment by hbh7** [comment]
Also validate that the returned data format adheres to https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Backend-Overview

**Comment by hbh7** [comment]
Coming soon: returned data spec, stay tuned.

**Comment by PrinxeShamar** [comment]
Would you need to be a site admin to call this route?

**Comment by hbh7** [comment]
I don't think so. My thoughts are that it'll just return name or something for anyone who tries to query someone else, I gotta figure it all out still. It'd be useful for listing people as part of a group, for example.
