### ISSUE TITLE
Style readonly inputs

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#387]
**Please describe what has to be done**
For example, on the account page, the username field is read only as we do not support changing usernames, but still want the user to be able to see what it is. We're setting the `readOnly` attribute on the field but it still looks like you could interact with it, even though you cant. 

**Additional context**
Perhaps the purple outline that it creates turns red instead? I think you can even turn the cursor to a crossed out circle or something.

**Comment by hbh7** [comment]
I've set it to December as it's not a huge priority but you're welcome to work on it now if you want.

**Comment by hbh7** [comment]
One note: It's probably best to style both `disabled` and `readonly` as apparently they're different. Read only means you can still click in the box and it gets sent with the form, whereas disabled you can't click it and it won't get sent with a form. I think we should primarily use readonly but there may be times when disabled makes more sense.

**Comment by Isaac-the-Man** [comment]
Maybe we can mark the input `disabled`, then have a `<input type="hidden">` set to the same value for sending forms.

**Comment by hbh7** [comment]
Notes from group meeting on 3/12/2021:
Let's stick with using `readOnly` for now. It seems to behave a bit more desirably in most cases at least. My understanding with CSS is that we should be able to style both with the same rules so let's do that as that should be trivial, and then would work in the future if/when we use `disabled`.

**Comment by hbh7** [comment]
Done in #431
