### ISSUE TITLE
Backend permission check functions

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#410]
**Please describe what has to be done**

- [x] Group permission check (user access)
- [x] Group permission check (admin edit) 
- [x] Poll permission check (user access)
- [x] Poll permission check (admin edit)

Should take in a user ID and a group/poll ID, and then check that the given ID has permission to do the stated task to the 2nd ID. Probably just return true/false based on the result. 

**Additional Details**
Put the functions at the end of groups.js or polls.js. Name them something like checkAccessPermission(userID, otherID), checkAdminPermission(userID, otherID) or similar consistent format.

**Comment by EthanTuttle** [comment]
I've done the first part, but we don't really have a way to define admins and polls seems to be solely tied to groups so that doesn't really seem necessary.

**Comment by hbh7** [comment]
Notes from 3/19/2021 meeting:
We talked about this and updated the DB schema to reflect that polls can be linked or not linked to groups, and store their admins internally if not group linked.

**Comment by hbh7** [comment]
Done in #446.
