### ISSUE TITLE
Backend /api/polls/:id/new Endpoint Todo Items

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#415]
**Please describe what has to be done**
Check out the endpoint and complete the TODO items in the code.

**Comment by hbh7** [comment]
Also validate that the returned data format adheres to https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Backend-Overview

**Comment by Isaac-the-Man** [comment]
I'm planning to use shcema validation npm package (joi)[https://www.npmjs.com/package/joi]. It's a really useful package for validating request body. For example writing a schema validation for the route `/api/polls/new` would be as easy as:
```js
  // Validate request body
  const schema = Joi.object({
    Name: Joi.string().alphanum().min(3).max(30).required()
  });
  const validResult = schema.validate(req.body);
  // invalidate handling
  if (validResult.error) {
    return res.status(404).send(validResult.error);
  }
```
It automatically generates error messages. Example below is sending an badly formatted key `Name`:
```
{
    "_original": {
        "Name": "HELLO@~!@"
    },
    "details": [
        {
            "message": "\"Name\" must only contain alpha-numeric characters",
            "path": [
                "Name"
            ],
            "type": "string.alphanum",
            "context": {
                "label": "Name",
                "value": "HELLO@~!@",
                "key": "Name"
            }
        }
    ]
}
```
This feel like is the easiest (and also consistent) to implement across the server, but I can always map it to the specified format.

**Comment by hbh7** [comment]
Notes from 2021/02/19 meeting:
This does look like it'd be super useful for our validation, so I think we should definitely try it out. The error messages should be able to be parsed pretty easily and pushed into our common backend data format (details.message -> error) so that can work too. Good find!
