### ISSUE TITLE
Login/Register with school dropdown doesn't work anymore 

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#420]
**Describe the bug**
The dropdown menu on the login with school and register with school pages no longer shows RPI in the list. It should at least show RPI in it. Not sure if this is a frontend or a backend issue at this time. 

**To Reproduce**
1. Go to https://pollbuddy.app/register/school or https://pollbuddy.app/login/school
2. Click on the menu box
3. See the list is empty

**Expected behavior**
There should at least be RPI in the dropdown list. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5050375/107446341-3c470900-6b0c-11eb-8dd4-94cc965f3378.png)
![image](https://user-images.githubusercontent.com/5050375/107446367-4c5ee880-6b0c-11eb-91f3-49230c57f37e.png)

**Additional Information**
Thanks to @EthanTuttle for finding this!

**Comment by Isaac-the-Man** [comment]
Looks like `list` is empty in file [PollBuddy-Server/backend/modules/schoolList.js](https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/backend/modules/schoolList.js)

**Comment by hbh7** [comment]
Indeed. This should be documented more clearly but what that does is it makes a list for other files like PollBuddy-Server/backend/modules/rpi.js then add to. Try the /api/schools endpoint and see if that returns anything.

**Comment by hbh7** [comment]
Seems it doesn't work either. I found this in the logs: 
![image](https://user-images.githubusercontent.com/5050375/107453967-0dd02a80-6b1a-11eb-85b9-7d5283aada92.png)

I think the backend is failing to launch due to a database issue. Eventually we'll want to have tests for this lol. I'll see if I can remove the offending data and hope that fixes it.

**Comment by hbh7** [comment]
Ok band-aid fix applied. Bit of a funny issue actually. I guess some people registered and there's a bug in the backend where it stores their usernames as "Username" whereas the indexes and the DB schema call for "UserName". For whatever reason, Mongo was not happy with that and seems to have caused the backend to crash over and over every time it tries to start up and create the index. 

I manually fixed it with `db.users.update({}, {$rename:{"Username":"UserName"}}, false, true);` but we'll want to fix the offending code or it's just going to happen again. Key places to look are in the `routes/users.js` file. There may be inconsistencies elsewhere that should be fixed alongside this. 

@Isaac-the-Man you're welcome to work on it if you'd like. Otherwise I can take care of it.

**Comment by Isaac-the-Man** [comment]
Sure I'll take a closer look

**Comment by hbh7** [comment]
Great, thanks! Should just be a matter of finding where the case is wrong. In general, database stuff is PascalCase and regular variables are camelCase. Slightly confusing, I know, but it made sense at the time.

**Comment by hbh7** [comment]
Fixed in #421
