### ISSUE TITLE
Fix positioning of Join Existing Group dialog on Groups page

### ISSUE THREAD

**Issue by jssunray34** [PollBuddy/PollBuddy#423]
**Describe the bug**
On the Groups page, the Join Existing Group dialog popup should be centered on the page. Right now, the positioning is absolute and hard coded to make it look centered on large screens, but this should be fixed so that the dialog is centered on all screen sizes.

**To Reproduce**
1. Go to Groups page.
2. Click on Join Existing Group.
3. The popup may or may not be centered. To see the issue, make the screen size smaller. The dialog shifts to the left.

**Expected behavior**
The Join Existing Group dialog should be centered on all screen sizes.

**Screenshots**
<img width="1329" alt="PollBuddy" src="https://user-images.githubusercontent.com/55996087/108916993-0cfcc580-75fd-11eb-95e6-0dd4071becf9.png">

**Comment by hbh7** [comment]
Perfect job creating the issue! :)

**Comment by EthanTuttle** [comment]
Closing this because issue #290 will make this irrelevant
