### ISSUE TITLE
Decide on a format for group invite codes

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#428]
**Please describe what has to be done**
Some things to consider:

- Length
- Character set
- If the length/charset overlap with the poll code, do we want a check for duplicates? Should we have a system of knowing if one is a poll code or a group invite code? 
- Should we allow user-generated group invite codes?
- Other details

Please leave thoughts below

**Comment by Isaac-the-Man** [comment]
The easiest way I can think of is just hashing the ObjectID (of the polls or group) with md5 and take the last 5 (probably enough to avoid collision) chars as the invite code. To distinguish between poll and group invite code we can just prepend 'p-' or 'g-' to the length-5 hash. As for user-generated code I don't it should be allowed.

**Comment by hbh7** [comment]
Replaced with #449.
