### ISSUE TITLE
validateID requires async support

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#460]
**Describe the bug**
When validateID was added/updated, something went wrong at some point and many usages aren't correct. Calls need to be made like `const id = await validateID("polls", req.params.id);` with the key difference being the added await, otherwise it returns a promise and not valid data. The endpoint also needs the `async` keyword added, like `router.get("/:id/view", async function (req, res, next) {` to support the await. Some of these have already been fixed, some remain. All should be updated.

**Comment by Isaac-the-Man** [comment]
I checked all the routes in branch backend but couldn't find an error. To avoid confusion I added the [documentation](https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Backend-Overview#validateidcollection-id).

**Comment by hbh7** [comment]
Oh great, maybe I fixed them all then. I didn't check lol, maybe I should have. Thanks :)
