### ISSUE TITLE
Fix the poll submission problems

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#470]
**Please describe what has to be done**
During prep for the demo, I found several things that didn't work right in the poll submission endpoint. I've left todo items in the code for everything I *think*, so these should just be attended to so the endpoint works as expected and in all cases.

**Comment by Isaac-the-Man** [comment]
It works fine for me though. Perhaps you are sending the Answers array in an object (like below)?
```json
{
  "Answers": [
    {
        "QuestionID": "q1_id",
        "Answer": "1234"
    },
    {
        "QuestionID": "q2_id",
        "Answer": "1234564"
    }
  ]
}
```
Because it should be just an array lol (something like below).
```json
[
  {
      "QuestionID": "q1_id",
      "Answer": "1234"
  },
  {
      "QuestionID": "q2_id",
      "Answer": "1234564"
  }
]
```
Sorry for making it confusing, do you want me to change it to fit the first example, it's a quick fix.

**Comment by hbh7** [comment]
I'd have to take a closer look at it to be sure. Whoever takes this issue, we can take a look together and decide what to do.
