### ISSUE TITLE
405 Method not allowed for all unused endpoint methods, and fix existing ones to use this status code

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#478]
**Please describe what has to be done**
Each endpoint should have a GET and a POST handler, but not both need to be used. Unused ones should be like this:
```
router.get("/login", function (req, res) {
  return res.status(405).send(createResponse(null, "GET is not available for this route. Use POST."));
});
```
Some exist for this already, but they might not be using the right code. 405 Method Not Allowed makes the most sense here I think, so let's standardize on that. I think there's an existing issue for creating these, so maybe these two issues can go together.

**Comment by EthanTuttle** [comment]
Should the invalid endpoints be added to the wiki? Or should we leave the wiki for only valid endpoints?

**Comment by hbh7** [comment]
I think it's good to have both listed just so it's as obvious as possible for everyone.

**Comment by hbh7** [comment]
Everything but the POST ones should be done in #483
