### ISSUE TITLE
Button to choose whether to log out everywhere on password change

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#481]
The frontend needs a checkbox toggle for this in the password changing area. It should also submit it to the backend along with the password change request. 

The password change request should be to backend's users/me/edit with type POST and the body as:
```
{
Password: String
LogOutEverywhere: Boolean
}
```
LogOutEverywhere can default to false/unchecked. 

Also see #562 for full edit route info

Edit 2021/11/09: Added additional notes

**Comment by NoDelicacyLoin** [comment]
how to self-assignee to this issue? didn't see the self assignee tab there

**Comment by hbh7** [comment]
Hi, you should be able to see an "Assignees" tab on the right side of your screen if you're on a desktop/laptop computer. This particular issue is already assigned to someone though, so you won't see the "assign yourself" button. Perhaps take a look at another?

**Comment by doboianh** [comment]
Can i clear this project ?

**Comment by hbh7** [comment]
@doboianh Looks like it's currently assigned to @lyndseytoft, so you'll have to find one that no one is currently assigned to. Sorry about that

**Comment by hbh7** [comment]
@lyndseytoft Let me know if this new spec makes sense. The backend won't properly accept the call so you don't have to worry about that, but you should be able to write the frontend code for it.

**Comment by lyndseytoft** [comment]
@hbh7 This looks good to me, I will let you know if I run into issues or questions!

**Comment by hbh7** [comment]
Done in #613
