### ISSUE TITLE
/polls/history is redirected incorrectly to /polls/history/view

### ISSUE THREAD

**Issue by jbsandling** [PollBuddy/PollBuddy#503]
**Describe the bug**
When you try to visit the Poll History page (which following App.js should be at /polls/history) you are instead taken to '/polls/history/view', a poll view page with the Poll ID of "history" because of the redirect introduced in #496. I assume a solution to this issue either means ensuring that "history" is not read as a poll ID, or changing the routing of the Poll History page (i.e. not immediately following /polls/).

**To Reproduce**
1. Go to  https://pollbuddy.app
2. Click on the 'Menu' dropdown in the top right
3. Select the 'History' link.

Or simply try to visit https://pollbuddy.app/polls/history

**Expected behavior**
This link should take you to the Poll History page, but instead redirects you to a poll view page for the poll with ID "history".

**Comment by hbh7** [comment]
Done in #505
