### ISSUE TITLE
CONTRIBUTING.md links to create new wiki page

### ISSUE THREAD

**Issue by SethLaurenceau** [PollBuddy/PollBuddy#514]
**Describe the bug**
the CONTRIBUTING.md page links to a page to create a new wiki page instead of sending the user to the wiki

**To Reproduce**
1. Go to https://github.com/PollBuddy/PollBuddy/blob/master/CONTRIBUTING.md
2. Click 'Here'
3. See error

**Expected behavior**
The link goes to the front page of the poll buddy wiki

**Comment by hbh7** [comment]
Good catch, thanks!
