### ISSUE TITLE
Contact Us page backend call

### ISSUE THREAD

**Issue by fanga2** [PollBuddy/PollBuddy#520]
We need to create a backend call in the Contact Us page which automatically retrieves the school of the user and fills in the school box if available.

**Comment by hbh7** [comment]
Auto filling name would be neat too, and if we have both then we probably can just use the user info route (/api/users/me) to get that info I think? Then we'd just have to make sure that one returns the right data. 

Also on that page, should we change phone to email and auto fill that too? Email seems much more applicable than phone number these days.

**Comment by fanga2** [comment]
Perhaps we should add a separate thing for email?

**Comment by hbh7** [comment]
Done in #536
