### ISSUE TITLE
LoadingWheel wiggles as it moves

### ISSUE THREAD

**Issue by lyndseytoft** [PollBuddy/PollBuddy#537]
As I was playing around which some code for the issue I was working on, I noticed the `LoadingWheel` object actually wiggles when it moves in a circle. This might not be the biggest deal, but this functionality was not intentional. See the gif below for an example. Here, the wheel is white which makes the wiggle much more noticeable when compared to the standard coloring of the traditional wheel all over the site.

![wheel-bug](https://user-images.githubusercontent.com/84807533/137564091-8a54dce1-dff3-4387-af35-6cd980ec736c.gif)

In order to see this for yourself, you can:
1. Go to Poll Buddy site
2. Click "Login" button
3. Login into your Poll Buddy account and from there you will see the wiggling loading wheel. 

Like I said before, the wiggling the loading wheel does is much less noticeable here then the picture above, but if you look closely, you will see that the wheel does not turn straight. It's pretty silly if you ask me.
For reference here is another picture of the wheel with the standard coloring.

![wheel-bug-2](https://user-images.githubusercontent.com/84807533/137564379-afa58b09-98c8-499f-bade-a526acb9db42.gif)

**Comment by hbh7** [comment]
Amazing find haha, can't wait to see what the solution ends up being

**Comment by hbh7** [comment]
Done in #543
