### ISSUE TITLE
/api/users/me fixes

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#549]
**Describe the bug**
When calling this route, such as from the contact us page automatically, the backend will crash as there's no test to see if a user is actually logged in before trying to get their ID from the session. There's actually a todo item in the code for it too. 

Also, it should return the following fields: 
- FirstName
- FirstNameLocked
- LastName
- LastNameLocked
- UserName
- UserNameLocked
- Email
- EmailLocked
- SchoolAffiliation

**Comment by PrinxeShamar** [comment]
NOTE: Update Documentation of this route

**Comment by PrinxeShamar** [comment]
NOTE: Should be camelCase Fields.

**Comment by hbh7** [comment]
Done in #627
