### ISSUE TITLE
Update copyright

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#551]
**Please describe what has to be done**
The copyright is outdated on the website. I'm thinking let's set it to "2019-(currentyear)", where (currentyear) is replaced with a dynamic calculation of the current year, so we never have to worry about it again.

**Comment by doboianh** [comment]
Can i do this issue ?

**Comment by sbolla2** [comment]
Sure I'll assign myself to a different one

**Comment by hbh7** [comment]
@doboianh looks like @therrance got it already, sorry about that.

**Comment by hbh7** [comment]
Done in #552
