### ISSUE TITLE
Document /me routes in the Users Router.

### ISSUE THREAD

**Issue by PrinxeShamar** [PollBuddy/PollBuddy#553]
Add documentation to the Wiki for the /me routes in the Users Router in the backend routes folder.

Routes include:
* /me
* /me/edit
* /me/groups

**Comment by hbh7** [comment]
On hold for a bit so I can better figure out the future of the edit routes

**Comment by hbh7** [comment]
Edit, me, and group routes now figured out

**Comment by SethLaurenceau** [comment]
Wiki page "Specifications ‐ Backend Routes (Users)" updated with new sections for /me/edit and /me/groups
