### ISSUE TITLE
About page typo

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#556]
**Describe the bug**
On the about page, there's a typo: "Students are susceptible to forgetting bring them to class". Should be: "Students are susceptible to forgetting to bring them to class"

**Additional Information**
This bug was found during the HCI usability testing!

**Comment by doboianh** [comment]
Can i do it ?

**Comment by hbh7** [comment]
@doboianh looks like @jamesbalcombe83 got it already, sorry about that.

**Comment by hbh7** [comment]
Done in #557
