### ISSUE TITLE
Backend route testing, fixing: users: /me/edit

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#562]
**Please describe what has to be done**
- [x] Should accept a JSON Object
* Only send changed fields
  * Accepted fields:
    * FirstName: String
    * LastName: String
    * UserName: String
    * Email: String
    * Password: String
    * LogOutEverywhere: Boolean (required if password is included, send error otherwise) 
		
 - [x] Backend should check for the existence of each key and validate each, and then if no errors, overwrite each saved value with the provided ones. 
 - [x] Upon success, return result = success and data as the same that /:id would give so the frontend can update its cache. Upon failure, return result = failure and error message as whatever the validation error is, or that there was a database problem.
 - [x] Please also note that the fields above are written in PascalCase to match the database data. However, the backend is a translation layer for the frontend, and therefore it should accept and return data in camelCase instead, as that is the format the frontend uses. This should simply mean changing the case of the first letter.
 - [x] Permissions should be checked. Here, this means make sure the user is logged in. 
 - [x] Special cases: 
   - [x] Protected Values:
     - [x] Should respect values that have a `<keyname>Locked` set to `true` by not allowing them to be changed. This applies to `FirstName`, `LastName`, `UserName`, and `Email`. Additionally, if `SchoolAffiliation` is set, `Password` changing should be locked too. 
   - [x] Resetting password: If a password is provided, it should be hashed as in the registration functions, and if `LogOutEverywhere` is set, the function `logOutEverywhere(userid);` should be called. 

Edit 2021/11/09: Added LogOutEverywhere info

**Comment by PrinxeShamar** [comment]
I believe we should accept a json object of the camelCase because thats like the same data we accept for login and register>

**Comment by PrinxeShamar** [comment]
We haven't specificied the data we want the /:id/ route to return? I'm guessing firstName, LastName, userName and email?

**Comment by hbh7** [comment]
> I believe we should accept a json object of the camelCase because thats like the same data we accept for login and register>

That's what the 4th checkbox means. The database fields are PascalCase, but the backend API should accept and return camelCase. 

> We haven't specificied the data we want the /:id/ route to return? I'm guessing firstName, LastName, userName and email?

True, we haven't, but this is about /me/edit. /:id/ is here: #347

**Comment by PrinxeShamar** [comment]
logOut everywhere would just be deleting the session?

**Comment by hbh7** [comment]
Deleting the user data in the session. You could delete the entire session but it's probably not necessary. The important thing is deleting that user's user data from __every__ section that has their user data.
