### ISSUE TITLE
Lock UserName in DB on signup

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#570]
**Please describe what has to be done**
Currently, the `UserNameLocked` field is not being set during registration. Given that we currently do not allow username changes, this should be set to `true` upon registration. 

Edit: `false` to `true`

**Comment by PrinxeShamar** [comment]
set to true* right?

**Comment by hbh7** [comment]
Lol yes, you're right, my apologies. Good catch
