### ISSUE TITLE
Backend reset password functions / routes

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#583]
**Please describe what has to be done**

# Route 1 - /api/users/forgotpassword
Just empty routes that are present to catch any accidental accesses. 

# Route 2 - /api/users/forgotpassword/submit 
We need a route in the backend to generate reset tokens from a given email/username, and store this request in the database. The tokens should be 32 randomly generated characters in the keyspace `A-Za-z0-9`. The tokens should be stored in the backend in the user's account under the `ResetPasswordToken` key, along with a `ResetPasswordTokenExpiration` that is based on the current (server) time + 1 hour. 

The account should be checked to exist before creating anything, and return the same response regardless. Assuming no database error, send a successful response with empty data, and a standard database error occurred message if one occurred. 

Use the `email` module's `send` function to send an email including a message about why they're receiving this email, how to continue resetting the password (by clicking on a pregenerated link that brings them to the appropriate frontend page and includes the reset token and their username, or by manually navigating to the relevant page and inputting the token and username), and what do do if this email was received in error (no action required, but please ensure that your email account is secured with a good password and ideally 2FA, just in case). Check out some examples from companies like Google, Microsoft, etc. for reference. Let me know if email sending functionality isn't available on the CI dev test instances and I'll make it available. 

# Route 3 - /api/users/forgotpassword/validate
This route should accept in the body the token from the user, `resetPasswordToken`, and their `username`. Then, it should validate if this is a valid token (exists for this user and is not expired), and if so, return success with empty data. If the token isn't found, or is invalid or expired, return failure with error message of "Token is invalid.". 

# Route 4 - /api/users/forgotpassword/change
This route should accept in the body the token from the user, `resetPasswordToken`, their `username`, and new `password`.. Then, it should validate if this is a valid token (exists for this user and is not expired), and if the password meets the requirements. If so, hash and save the password, then delete the reset password token and expiration date from the database, and return success. If the token isn't found, or is invalid or expired, return failure with error message of "Token is invalid.". Do not automatically log the user in, they will have to do that separately.

**Comment by SethLaurenceau** [comment]
additional work to be done:
send the token to the user's email
rename password token to security code
have email redirect to login/reset page
have some indication on reset page that an email has been sent
verify that the front end page properly talks to the backend routes(vague, I know, but its worth checking if anything could cause issue at the frontend-backend border)

**Comment by hbh7** [comment]
Done in #680
