### ISSUE TITLE
Backend /api/users/me/groups reworking

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#591]
**Please describe what has to be done**
Change the get route for this to look through the groups collection for groups that have the currently logged in user's ID in the group's `Members` array, and the group's `Admins` array. Return data like:
```
{ "result": "success",
  "data": {
    "admin": [ 
      { 
        "id": <group ID>,
        "name": <group name>
      }
      ... more objects ...
    ],
    "member": [ 
      { 
        "id": <group ID>,
        "name": <group name>
      }, 
      ... more objects ...
    ]
  } 
}
```

**Comment by PrinxeShamar** [comment]
Also add new tests for the update.
