### ISSUE TITLE
TimeLimit should be updated to interpret a date

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#595]
**Please describe what has to be done**
TimeLimit used to be a number of seconds, but now it will be a date object, so the frontend should accept a date object, convert it to seconds by finding the difference between the TimeLimit and now, and displaying it as it currently does. Optionally, it could even display the deadline alongside the countdown, but this isn't strictly necessary. 

**Additional context**
Related: #594

**Comment by hbh7** [comment]
Code to create a test poll (paste into the Chrome/Firefox developer JavaScript console): 

```
fetch('http://localhost:7655/api/polls/new', {
  method: 'POST',
  body: JSON.stringify({"Name": "Test Poll 1"}),
  headers: {
    'Content-type': 'application/json; charset=UTF-8'
  }
})
.then(res => res.json())
.then(console.log)

fetch('http://localhost:7655/api/polls/<the ID from the previous command>/edit', {
  method: 'POST',
  body: JSON.stringify({"Action": "Add", "Questions": [ { "QuestionNumber": 1, "Visible": true, "QuestionText": "What is the correct answer?", "AnswerChoices": [ "One", "Two", "Three" ], "CorrectAnswers": [ "One"], "MaxAllowedChoices": 1, "TimeLimit": 10000 } ] }),
  headers: {
    'Content-type': 'application/json; charset=UTF-8'
  }
})
.then(res => res.json())
.then(console.log)
```

**Comment by dyamijr** [comment]
fetch('http://localhost:7655/api/polls/new', {
  method: 'POST',
  body: JSON.stringify({"Name": "Test Poll 1"}),
  headers: {
    'Content-type': 'application/json; charset=UTF-8'
  }
})
.then(res => res.json())
.then(console.log)


fetch('http://localhost:7655/api/polls/<the ID from the previous command>/edit', {
  method: 'POST',
  body: JSON.stringify({"Questions": [ { "QuestionNumber": 1, "Visible": true, "QuestionText": "What is the correct answer?", "AnswerChoices": [ "One", "Two", "Three" ], "CorrectAnswers": [ "One"], "MaxAllowedChoices": 1, "TimeLimit": <enter number>} ] }),
  headers: {
    'Content-type': 'application/json; charset=UTF-8'
  }
})
.then(res => res.json())
.then(console.log)

**Comment by hbh7** [comment]
@dyamijr Looks like there's an issue for the backend fixing we did, #594. Make a note of that one in your PR too since you'll have done 2 issues :)

**Comment by hbh7** [comment]
Other discussion notes: 
https://www.epochconverter.com/
JS Dates: now() Returns the number of milliseconds since midnight Jan 1, 1970, setTime() Sets a date to a specified number of milliseconds after/before January 1, 1970
