### ISSUE TITLE
Account tab is just a loading wheel

### ISSUE THREAD

**Issue by lyndseytoft** [PollBuddy/PollBuddy#612]
When making your way to the "Account Info" tab after logging in, the entire page is just a loading wheel loading.

**To Reproduce**
1. Click on deployment website
2. Log into Poll Buddy
3. Click on "Menu" button on top right hand side of screen
4. Click on "Account" from the dropdown items
5.  See loading wheel error

Not sure what's going on here, but I assume this was just an oversight when a pull request changing the Account tab was made.

Here is a picture of the current page: 
![image](https://user-images.githubusercontent.com/84807533/145324804-cff80c12-49fb-4f91-92ba-4dc5a5701e2b.png)

I don't know exactly when this began to occur, however I noticed it once I began to make a pull request into master which would alter the "Account Info" page.  Happy coding :)

**Comment by JMozes16** [comment]
This appears to be fixed.

**Comment by hbh7** [comment]
Awesome, maybe it was a backend feature not working that caused it and was fixed, not sure.
