### ISSUE TITLE
Update /me, /me/edit Routes documentation

### ISSUE THREAD

**Issue by PrinxeShamar** [PollBuddy/PollBuddy#614]
Update /me, /me/edit according to these issues.

https://github.com/PollBuddy/PollBuddy/issues/562
https://github.com/PollBuddy/PollBuddy/issues/549

**Comment by shreyabarua** [comment]
Updated documentation to reflect changes mentioned in the linked issues.

Also reformatted documentation across all wiki pages to be uniform. See https://docs.google.com/document/d/1opTKqG60Er7Ct3EOtfuJl6XXWujx6RIKlIaK86QLG5s/edit?usp=sharing for more details
