### ISSUE TITLE
More User Router Tests and Coverage

### ISSUE THREAD

**Issue by PrinxeShamar** [PollBuddy/PollBuddy#620]
**Is your feature request related to a problem? Please describe.**
Currently we have 50% on the user.js router and User Model. A great first issue is to increase test coverage by writing more tests and increasing the coverage in this files. You can see what lines are not tested and write tests that would run there. 

**Describe the solution you'd like**
* Several additional Tests in the user.test.js file

**Additional context**
Reference the Backend Testing page on the Wiki for more information on writing/running tests. This is a great issue for exploring the code and understanding how one of the main routers work in PollBuddy. Also gives you experience with writing tests and using the testing framework.

**Comment by hbh7** [comment]
Done in #638
