### ISSUE TITLE
Poll view page should check if the poll is public frontend

### ISSUE THREAD

**Issue by JaBeast13** [PollBuddy/PollBuddy#625]
**Describe the bug**
When trying to access a poll when not logged in, the error 

**To Reproduce**
Create a local instance of a private poll and try to access it without being logged in

**Expected behavior**
If trying to access a private poll and not logged in, user should be redirected to the login page.

**Screenshots**
This is currently what happens if you try to access a private poll when not logged in.
![image](https://user-images.githubusercontent.com/78986694/153676023-c9bd0cf3-a670-4d9a-bcff-810483d7ae27.png)

**Additional context**
This is the link to the old issue which fixed the backend.
(https://github.com/PollBuddy/PollBuddy/issues/599)

Here's a DBD(Database) command you can run to create test polls:
db.polls.insertOne({"Name": "Test Poll", "Questions": [ { "QuestionNumber": 1, "Visible": true, "QuestionText": "Enter question text here.", "AnswerChoices": ["Answer 1", "Answer 2", "Answer 3"], "CorrectAnswers": [ "Answer 2" ], "MaxAllowedChoices": 1, "TimeLimit": 10000 } ], Public: true })
Key thing to change for this would just be Public: true to be Public: false to test both cases. I can also show how to connect to the DB directly to run the command (dev mode only).

**Comment by hbh7** [comment]
Done in #659
