### ISSUE TITLE
Backend 404 page should be in our response format

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#628]
**Please describe what has to be done**
Visiting something like https://pollbuddy.app/api/test (a deleted endpoint) yields "Not Found". It'd be better to wrap it in our "result" and "error" json format.

**Comment by khirupa** [comment]
Hi, this is my first issue on Github, and I am willing to work on it. Could you please assign me this issue?

**Comment by hbh7** [comment]
Done in #631, thanks @khirupa!
