### ISSUE TITLE
Frontend Not Found page not working

### ISSUE THREAD

**Issue by JMozes16** [PollBuddy/PollBuddy#629]
**Describe the bug**
When going to a page that isn't defined, the Not Found page does not pop up.

**To Reproduce**
1. Go to http://localhost:7655/polls or any other non-existent page.

**Expected behavior**
The Not Found error message should appear.

**Screenshots**
Current:
![CurrentNotFound](https://user-images.githubusercontent.com/85561037/154769695-6c64b370-4a05-430f-ace1-1984faafe9ac.PNG)

Actual NotFound:
![NotFoundPage](https://user-images.githubusercontent.com/85561037/154769744-bfed4a3a-5691-4568-9be0-4f7a56937948.PNG)

**Additional context**

**Comment by hbh7** [comment]
Fixed in #630
