### ISSUE TITLE
Show Group Details on Group Join

### ISSUE THREAD

**Issue by PrinxeShamar** [PollBuddy/PollBuddy#651]
**Describe the solution you'd like**
We would like to display some of the group information (Group Name and Group Description) to users on the group join. So after they click the Join Group button there would be a call to the Get Group API endpoint and transfer to the confirm page. On the confirm page display the data and once they click join call the Join Group endpoint.

**Tasks**

- [ ] Call Get Group API Endpoint
- [ ] Display Group Data on the confirm page

**Files of Interest**
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/backend/routes/groups.js
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/frontend/src/pages/GroupJoin/GroupJoin.js

**Comment by BillyMerchan** [comment]
Issue seems to have been solved in master branch
