### ISSUE TITLE
Show total number of responses to polls

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#653]
**Please describe what has to be done**
Add a total responses counter to the results page of polls. May need a backend endpoint

**Comment by PrinxeShamar** [comment]
**Files of Interest**
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/backend/models/Poll.js
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/frontend/src/pages/PollResults/PollResults.js
