### ISSUE TITLE
Change Delete Poll Button text to "Delete Poll"

### ISSUE THREAD

**Issue by JaBeast13** [PollBuddy/PollBuddy#674]
**Describe the bug**
Delete poll button does not specify it deletes the poll

**To Reproduce**
When editing a poll as an admin, there will be the button to delete the poll

**Expected behavior**
Button should say "Delete Poll"

**Screenshots**
![image](https://user-images.githubusercontent.com/78986694/162529169-fe6d74d5-9072-43c6-8213-f1248faeb9c7.png)

**Additional context**
N/A

**Comment by hbh7** [comment]
Done in #683
