### ISSUE TITLE
(Quick Start) User Guide

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#689]
**Please describe what has to be done**
A professor has expressed interest in using Poll Buddy in their classes, but we do not have amazing user documentation to refer them to. I'd like to have a user guide for how to use the application as a normal user, or a professor as an example. A quick start guide would be a good supplement as well.

This guide should have information about what the terminology is (groups, polls, questions, etc.), how they can get started on the platform creating groups and polls, and how others can join the group to answer these questions.

**Comment by Curtex02** [comment]
I want to add an option to the menu drop list, the "quick start guide" button. 
I want this to bring users to a new page with two simple text boxes.
One will be for admins, one will be for members.
The text boxes will be a list of instructions for how to use the website

**Comment by hbh7** [comment]
Done in #709
