### ISSUE TITLE
Poll viewer is empty when there are no questions

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#695]
**Please describe what has to be done**
When you try to view a poll without any questions, it just renders a blank page. It should show an error message stating that the poll admin did not configure any questions for the poll or something. Or maybe "This poll has no questions for you to answer at this time."

**Comment by pprathameshmore** [comment]
@hbh7 I would like to work on this!

**Comment by hbh7** [comment]
@pprathameshmore you got it!

**Comment by hbh7** [comment]
@pprathameshmore sorry, this is one of those things that isn't incredibly obvious yet unfortunately. If you are in the poll editor page after creating, the ID is in the URL, like pollbuddy.app/polls/<id>/edit

**Comment by pprathameshmore** [comment]
@hbh7 Whenever I enter that ID. It throws a validation error!

![image](https://user-images.githubusercontent.com/17108186/170089720-601784a6-4229-4c0d-933e-7763f7a25d21.png)

**Comment by hbh7** [comment]
@pprathameshmore uhhhh good point, we haven't actually tried using that in a long time, and I don't think it's fully (or partially) implemented in the backend yet. Skip that and just replace the `edit` in the URL with `view`, and you'll be taken to the poll viewer page

**Comment by pprathameshmore** [comment]
@hbh7 Thank you! We can implement logic to generate a Poll ID with 6 characters on the backend side and show it on the frontend!
