### ISSUE TITLE
Poll Edit Buttons

### ISSUE THREAD

**Issue by PrinxeShamar** [PollBuddy/PollBuddy#748]
**Is your feature request related to a problem? Please describe.**
Currently the poll editor buttons at the bottom of the left side are in a weird form 2 buttons then 1 then 2 again. 

**Describe the solution you'd like**
We would like for buttons to be stack on another like how it is in other places in the app.

**Additional context**
[Poll Edit Component](https://pollbuddy.app/polls/6325f6bb237a84dff0951e04/edit)

**Comment by andrewkykoo** [comment]
@PrinxeShamar Hi Shamar, I would like to work on this issue. I read the contribution guide but wasn't able to self-assign any issues. Am I missing a step? Thanks!

**Comment by andrewkykoo** [comment]
> Hey @andrewkykoo, went ahead and assigned you to the issue. Let me know if you have any questions.

@PrinxeShamar, Is there a test/sample account/credential I can use?

**Comment by PrinxeShamar** [comment]
Hey @andrewkykoo you can just create a new PollBuddy account. If its on your local development environment this won't affect the actually pollbuddy database so you can create as many test accounts as your need.
