### ISSUE TITLE
session/local storage addition for teacher and users

### ISSUE THREAD

**Issue by blargwargyarg** [PollBuddy/PollBuddy#89]
Will need to add specifications for logins for teachers and regular users.

**Comment by hbh7** [comment]
What exactly does this entail? Do we need a (partial) group discussion?

**Comment by blargwargyarg** [comment]
Would differentiate which pages which types of users could access thats
basically it lol

**Comment by hbh7** [comment]
I believe the sessions are now handled by express-session, and store/will store who a person is, and then permission checks can be implemented.
